### ISSUE TITLE
Ability to group by multiple items

### ISSUE THREAD

**Issue by sztanko** [sztanko/cubedb#1]
Currently when getting aggregates, the output is something like this:
```yaml
result:
   column1:
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
   column2:
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
```

The task is to add a possibility to add further grouping for each column, that is:
1. add ```group_by``` attribute in api request, which would specify by which columns we would like to group the output by.
2. The output then should look like this:
```yaml
result:
   column1:
       group_by_column1_value_1:
          group_by_column2_value_1:
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
          group_by_column2_value_2:
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
       group_by_column1_value_2:
          group_by_column2_value_1:
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
          group_by_column2_value_2:
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
             value1:
                   metric1: 23
                   metric2: 1
             value2:
                  metric1: 12
                  metric2: 245
```
etc.
